[package]
name = "rusthead"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
http = "1"
rand = "0.8"
rinja = { version = "0.3", default-features = false }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
url = { version = "2", features = ["serde"] }
