[package]
name = "rusthead"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
http = "1"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.34"
toml = "0.8"
url = { version = "2", features = ["serde"] }
