services:
  {{ Self::service_name() }}:
    image: docker.verbis.dkfz.de/cache/traefik:latest
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/configuration/
      - --api.dashboard=false
      - --accesslog=true
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --tls.stores.default.defaultCertificate.certFile=/certs/fullchain.pem
      - --tls.stores.default.defaultCertificate.keyFile=/certs/privpem.pem
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/dashboard/`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      # TODO:
      # - "traefik.http.routers.dashboard.middlewares=auth"
      # - "traefik.http.middlewares.auth.basicauth.users=${LDM_AUTH}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - {{ tls_dir.as_path().display() }}:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro