services:
  {{ Self::service_name() }}:
    image: docker.verbis.dkfz.de/cache/traefik:latest
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/configuration/
      - --api.dashboard=false
      - --accesslog=true
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    labels:
      - "traefik.enable=true"
      {% for (middleware, encoded_auth) in basic_auth_users -%}
        - "traefik.http.middlewares.{{ middleware }}.basicauth.users={{ middleware }}:{{ encoded_auth }}"
      {%- endfor %}
    ports:
      - 80:80
      - 443:443
    configs:
      - source: certificates.yaml
        target: /configuration/certificates.yaml
    volumes:
      - {{ tls_dir|path }}:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

configs:
  certificates.yaml:
    content: |
      tls:
        stores:
          default:
            defaultCertificate:
              certFile: /certs/fullchain.pem
              keyFile: /certs/privkey.pem